node {

    checkout scm

    env.DOCKER_API_VERSION="1.24"

    //sh "git rev-parse --short HEAD > commit-id"

    //tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    tag = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
    appName = "puzzle"
    registryHost = "192.168.49.2:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    // latestImage = "${registryHost}${appName}:latest"

    env.BUILDIMG=imageName
    env.BUILD_TAG=tag

    stage("Build") {
        sh "docker build -t ${imageName} applications/puzzle"
        //sh "docker build -t ${imageName} -t ${latestImage} -f applications/puzzle/Dockerfile applications/puzzle"
        println "Build docker completed."
    }

    stage("Push") {
        sh "docker push ${imageName}"
        //sh "docker push ${latestImage}"
    }

    stage("Deploy") {
        //kubernetesDeploy configs: "applications/${appName}/k8s/*.yaml", kubeconfigId: 'kenzan_kubeconfig'
        sh "echo Deploying application..."
        
        sh "kubectl config view"
        sh "kubectl get nodes"
        sh "kubectl apply -f applications/${appName}/k8s/"
        sh "kubectl rollout restart deployment/${appName}"
    }    
}
