
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitor-scale
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: puzzle-scaler-cluster-role
rules:
  - apiGroups:
    - "apps"
    resources:
      - deployments
      - deployments/scale
    verbs:
      - update
      - get
  - apiGroups:
    - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch


---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitor-scale-puzzle-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: puzzle-scaler-cluster-role
subjects:
- kind: ServiceAccount
  name: monitor-scale
  namespace: default
