node {

    checkout scm

    env.DOCKER_API_VERSION="1.24"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-kenzan"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage("Build") {
        sh "docker build -t ${imageName} ."
    }

    stage("Push") {
        sh "docker push ${imageName}"
    }

    stage("Deploy") {
        sh "sed 's#__IMAGE__#'$BUILDIMG'#' k8s/deployment.yaml | kubectl apply -f -"
    }
}