node {

    checkout scm

    env.DOCKER_API_VERSION="1.24"
    
    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-kenzan"
    registryHost = "127.0.0.1:30912/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage("Build") {
        sh "docker build -t ${imageName} part1/hello-kenzan"
    }

    stage("Push") {
        sh "docker push ${imageName}"
    }

    stage("Deploy") {
        sh 
        if kubectl get svc hello-kenzan > /dev/null 2>&1; then
            echo "Service hello-kenzan already exists."
        else
            echo "Service hello-kenzan does not exist, it may need to be created."
        fi

        "sed 's#__IMAGE__#'$BUILDIMG'#' part1/hello-kenzan/k8s/deployment.yaml | kubectl apply -f -"
    }
}